### ISSUE TITLE
Foreman-proxy fails to start with gem conflict error.

### ISSUE THREAD

**Issue by mrbetta** [opnsense/ports#173]
Foreman_proxy installed from package or source fails to start with a gem conflict error in Sinatra. Uninstalling either still fails.

FreeBSD 13.1-RELEASE-p7
Used with OPNSense

```
Starting foreman_proxy.
root@OPNsense:/usr/local/etc/pkg/repos # /usr/local/lib/ruby/site_ruby/3.1/rubygems/specification.rb:2295:in `raise_if_conflicts': Unable to activate sinatra-3.0.5, because rack-3.0.7 conflicts with rack (~> 2.2, >= 2.2.4) (Gem::ConflictError)
        from /usr/local/lib/ruby/site_ruby/3.1/rubygems/specification.rb:1424:in `activate'
        from /usr/local/lib/ruby/site_ruby/3.1/rubygems.rb:209:in `rescue in try_activate'
        from /usr/local/lib/ruby/site_ruby/3.1/rubygems.rb:202:in `try_activate'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:154:in `rescue in require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:39:in `require'
        from /usr/local/share/foreman-proxy/lib/smart_proxy_main.rb:35:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/sbin/smart-proxy:6:in `<main>'
/usr/local/lib/ruby/site_ruby/3.1/rubygems/specification.rb:2295:in `raise_if_conflicts': Unable to activate sinatra-3.0.5, because rack-3.0.7 conflicts with rack (~> 2.2, >= 2.2.4) (Gem::ConflictError)
        from /usr/local/lib/ruby/site_ruby/3.1/rubygems/specification.rb:1424:in `activate'
        from /usr/local/lib/ruby/site_ruby/3.1/rubygems.rb:203:in `try_activate'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:154:in `rescue in require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:39:in `require'
        from /usr/local/share/foreman-proxy/lib/smart_proxy_main.rb:35:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/sbin/smart-proxy:6:in `<main>'
<internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sinatra (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/share/foreman-proxy/lib/smart_proxy_main.rb:35:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.1/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/sbin/smart-proxy:6:in `<main>'
```

**Comment by fichtner** [comment]
FreeBSD ports issue if it even exists. Not marked upstream because not used by us.
